// Drizzle ORM schema definitions — Better Auth tables only (games/moves live in Convex).

// Import Better Auth tables for use in schema object and foreign key references
import {
  user,
  session,
  account,
  verification,
  userRelations,
  sessionRelations,
  accountRelations,
} from "./auth";

/** Drizzle schema object passed to `drizzle()` and Better Auth's drizzle adapter. */
const schema = {
  user,
  session,
  account,
  verification,
};

export {
  // Better Auth tables (generated by @better-auth/cli)
  user,
  session,
  account,
  verification,
  userRelations,
  sessionRelations,
  accountRelations,
  // Legacy export name for backward compatibility
  user as betterAuthUser,
  schema,
};
